update

diff --git a/cloudbuild.yaml b/cloudbuild.yaml
--- a/cloudbuild.yaml
+++ b/cloudbuild.yaml
@@ -9,7 +9,9 @@
 # 2) Need to convert to use docker as gcloud will not run
 
 # 3) Can it reach modulesf declared in the higher folders?
+
 # 4) If yes, Modules can be versioned in separate folders and we can upgrade modules per tier.
+
 # 5) replicate this in every project in every tier.
 
 # 6) Understand the branching strategy and GitHub "codeowners" options
@@ -17,6 +19,8 @@
 # 7) NOTE that in the backend.tf file, the state file has prefix = "env/dev/foso"
 
 #     I assume this can be done for every project in every tier thereby separating the state files
+
+ 
 
 ## SB END
 
@@ -62,8 +66,24 @@ steps:
 
         echo "${d} might succeed: ${config}  found."
 
+        gcloud builds submit $d --config=${config}
+
+        if [[ $? -ne 0 ]]; then
+
+          echo "$d failed"
+
+        else
+
+          echo "$d passed"
+
+        fi
+
       fi
 
     done
 
     echo "All builds succeeded."
+
+#SB Need to see what this does? Does it tag the build
+
+#tags: ['$_PR_NUMBER', '$_REPO_OWNER', '$_REPO', '$_SHA', 'cloud-builders-community']
